# -*- coding: utf-8 -*-
"""text-to-image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHhruYErvy852gl8rH51F1jnEJwU3UxA
"""

!pip install diffusers transformers accelerate gradio --upgrade
!pip install safetensors

import torch
from diffusers import StableDiffusionPipeline
import gradio as gr

from huggingface_hub import login
# login("")

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe = pipe.to("cuda")

def generate_image(prompt):
    print(f"Generating image for prompt: '{prompt}'")
    image = pipe(prompt).images[0]
    print("Image generation complete.")
    return image

custom_css = """
.gradio-container {
    max-width: none !important;
}
"""

with gr.Blocks(theme="gradio/monochrome", css=custom_css) as demo:

    with gr.Row():
        gr.Markdown(
            """
            #  AI Text-to-Image Generator
            A demonstration of the Stable Diffusion model for project submission.
            """
        )

    gr.Markdown("---")


    with gr.Row():
        with gr.Column(scale=2):
            prompt_input = gr.Textbox(
                label="Enter your prompt",
                placeholder="e.g., A high-quality photo of an astronaut riding a horse",
                lines=3
            )
            submit_button = gr.Button("Generate Image", variant="primary")
            gr.Examples(
                examples=[
                    "A high-quality photo of an astronaut riding a horse",
                    "A pencil sketch of a cat playing a piano",
                    "A watercolor painting of a futuristic city"
                ],
                inputs=prompt_input
            )
        with gr.Column(scale=3):
            image_output = gr.Image(label="Generated Image")

    gr.Markdown("---")
    gr.Markdown(
        """
        <div style='text-align: center;'>
            <p>Powered by:</p>
            <a href='https://huggingface.co/docs/diffusers' target='_blank'>
                <img src='https://huggingface.co/front/assets/huggingface_logo-noborder.svg' alt='Hugging Face Diffusers' style='height: 40px; display: inline-block; margin: 10px;'>
            </a>
            <a href='https://pytorch.org/' target='_blank'>
                <img src='https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg' alt='PyTorch' style='height: 40px; display: inline-block; margin: 10px;'>
            </a>
            <a href='https://www.gradio.app/' target='_blank'>
                <img src='https://www.gradio.app/_app/immutable/assets/gradio.CHB5adID.svg' alt='Gradio' style='height: 40px; display: inline-block; margin: 10px;'>
            </a>
        </div>
        """
    )

    submit_button.click(
        fn=generate_image,
        inputs=prompt_input,
        outputs=image_output
    )


demo.launch(debug=True, inbrowser=True)